# Generated by Django 5.0.7 on 2024-09-05 09:17

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_story_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='total_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='total_reading_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='reading_level',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
