# Generated by Django 5.0.7 on 2024-09-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_readingsession_total_errors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reading_level',
            field=models.FloatField(default=0),
        ),
    ]
