# Generated by Django 5.0.7 on 2024-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_reading_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reading_level',
            field=models.FloatField(),
        ),
    ]
