# Generated by Django 5.0.7 on 2024-09-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_readingsession_current_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_reading_level',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
